services:
  postgres:
    image: "postgres:latest"
    volumes:
      - ~/volumes/codecake/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=codecake
      - POSTGRES_USER=codecake
      - POSTGRES_DB=airbnb-clone-backend-postgres-1
    ports:
      - 127.0.0.1:5443:5432
