logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    fr.codecake.airbnbcloneback: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-clone-back
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
    url: jdbc:postgresql://localhost:5443/airbnb_clone
    username: codecake
    password: codecake
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: airbnb_clone
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080
